require:
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/**/*.rb'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 12

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 5

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
