transfer_ids:
  "Bancomat-Bezug": "ddc82881-5543-4935-b3ec-607478b0b8e7"
  "Lastschriftverfahren VISECA CARD SERVICES SA": "17648175-aaa9-4885-9bff-1cd4743af9c5"
  "Konto CH6680808007186334417": "8d06a853-363f-4ad7-b5b6-fcab7308c9f1"
email_parts_regexps:
  entry_type: "(Belastung|Gutschrift)"
  account: "Konto:\\s(.*)\n"
  amount: "Betrag:\\s([0-9\\.']*)\\sCHF\n"
  booking_date: "Buchungsdatum:\\s([0-9]{2}\\.[0-9]{2}\\.[0-9]{4})\n"
  valuta_date: "Valutadatum: ([0-9]{2}\\.[0-9]{2}\\.[0-9]{4})\n"
  memo: "Buchung:\n(.*)\nFreundliche"
#  saldo: "Neuer Saldo:\\s([0-9\\.']*).*\n"
payee_name_regexps:
  - "\\nan:?\\s([\\w\\s]*)\\n"
  - "^Einkauf\\s(.*)\\n"
  - "E-Banking\\sAuftrag\\s\\(eBill\\)\\n(.*)\\n"
  - "Gutschrift\\s(.*)\\n"